---
http:
  server:
    address: '0.0.0.0'
    port: 8000
log:
  formatter: 'json'
  #| Facility | Keyword |
  #----------------------
  #|        0 | Panic   |
  #----------------------
  #|        1 | Fatal   |
  #----------------------
  #|        2 | Error   |
  #----------------------
  #|        3 | Warn    |
  #----------------------
  #|        4 | Info    |
  #----------------------
  #|        5 | Debug   |
  #----------------------
  #|        6 | Trace   |
  #----------------------
  level: 6
  fluentd:
    host: 'fluentd'
    port: 24224
kafka:
  bootstrap:
    servers: 'kafka'
  consumer:
    auto:
      offset:
        reset: 'earliest'
    topics:
    - 'bank'
    group:
      default:
        id: 'bank'
    readtimeout: 1000
  producer:
    topic: 'bank'
  perf:
    jobs: 1000
mongo:
  host: 'mongo'
  port: 27017
  user: 'example'
  passwd: 'example'
  db: 'bank'
  collection: 'checking_account'

