---
http:
  server:
    address: '0.0.0.0'
    port: 8000
  router:
    allowed_origins:
    - "https://*"
    - "http://*"
    allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    allowed_headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-CSRF-Token"
    exposed_headers:
    - "Link"
    allow_credentials: false
    max_age: 300
log:
  formatter: 'json'
  caller: true
  #| Facility | Keyword |
  #----------------------
  #|        0 | Panic   |
  #----------------------
  #|        1 | Fatal   |
  #----------------------
  #|        2 | Error   |
  #----------------------
  #|        3 | Warn    |
  #----------------------
  #|        4 | Info    |
  #----------------------
  #|        5 | Debug   |
  #----------------------
  #|        6 | Trace   |
  #----------------------
  level: 6
  fluentd:
    host: 'fluentd'
    port: 24224
kafka:
  bootstrap:
    servers: 'kafka'
  consumer:
    auto:
      offset:
        reset: 'earliest'
    topics:
    - 'bank'
    group:
      default:
        id: 'bank'
    readtimeout: 1000
  producer:
    topic: 'bank'
  perf:
    jobs: 1000
mongo:
  host: 'mongo'
  port: 27017
  user: 'example'
  passwd: 'example'
  db: 'bank'
  collection: 'checking_account'

